#Sample .travis.yml for R projects

env:
  global:
    - MAKEFLAGS="-j 2"
    - _R_CHECK_FORCE_SUGGESTS=0
language: r
r: 
  - release
  - devel
r_packages:
  - devtools
package: cache
bioc_required: true
r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-manual --timings"
-os:
  - linux
  - osx
before_install:
  Rscript -e 'update.packages(ask = FALSE)'
sudo: required
apt_packages: libudunits2-dev
after_success:
    - Rscript -e 'covr::codecov(token = "aec4300e-45cb-4373-9b0a-02df5f3561db")'
