#Sample .travis.yml for R projects

language: r
r: 3.3.0
package: cache
bioc_required: true
r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"
-os:
  - linux
  - osx