#Sample .travis.yml for R projects

language: r
r: 
  - release
  - devel
package: cache
r_packages:
  - covr
bioc_required: false
r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-manual --timings"
-os:
  - linux
  - osx
before_install:
  Rscript -e 'update.packages(ask = FALSE)'
sudo: required
apt_packages: libudunits2-dev
after_success:
    - Rscript -e 'covr::codecov()'
