# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' costFor
#'
#' Wrapper for deconvolution cost function using the Armadillo C++ library.
#'
#' @param oneMultiplet Integer; a integer vector of rounded counts per million
#' for one multiplet.
#' @param singletSubset Matrix; Numeric matrix with the preallocated singlets.
#' Each of the n synthetic multiplets should be stacked, i.e. rbind.
#' @param fractions Numeric; a numeric vector with length equal to
#' ncol(singlets) indicating the fractions that each column should be
#' multiplied with.
#' @param n Integer; length 1 integer indicating the number of synthetic
#' multiplets to generate.
#' @author Jason T. Serviss
#' @export
costFor <- function(oneMultiplet, singletSubset, fractions, n) {
    .Call('_sp_scRNAseq_costFor', PACKAGE = 'sp.scRNAseq', oneMultiplet, singletSubset, fractions, n)
}

#' sampleSingletsArma
#' 
#' This function takes a character vector of classes/cell with the same order
#' as the cells in the counts matrix. It returns one random index per unique
#' class and returns them as a integer vector.
#'
#' @param classes Character; a character vector of classes with length equal to
#' the number of cells for which counts exist.
#' @author Jason T. Serviss
#' @export
sampleSingletsArma <- function(classes) {
    .Call('_sp_scRNAseq_sampleSingletsArma', PACKAGE = 'sp.scRNAseq', classes)
}

#' subsetSingletsArma
#' 
#' This function takes a counts matrix and subsets the columns according to the
#' indices provided by the idxToSubset argument.
#'
#' @param singlets Matrix; a counts matrix with cells/samples as columns and 
#' genes as rows.
#' @param idxToSubset Integer; the indexes of cells/samples to be subset. 
#' @author Jason T. Serviss
#' @export
subsetSingletsArma <- function(singlets, idxToSubset) {
    .Call('_sp_scRNAseq_subsetSingletsArma', PACKAGE = 'sp.scRNAseq', singlets, idxToSubset)
}

